version: 0.2

env:
  variables:
    NODE_ENV: test

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
      - npx playwright install --with-deps

  build:
    commands:
      - npx playwright test || true

  post_build:
    commands:
      - npx tdpw upload ./playwright-report --token="$TESTDINO_TOKEN"

artifacts:
  files:
    - playwright-report/**/*
    - test-results/**/*
  discard-paths: no

reports:
  playwright-results:
    files:
      - playwright-report/report.json
    file-format: TESTNGXML
